name: Config Management Camp
location: Gent, Belgium
start: 2018-02-05
end: 2018-02-07
tags: ansible
description: |
  Config Management Camp.eu is the event for people interested in Open Source Configuration management to meet each other. CfgMgmtCamp.eu will be the event where different communities will meet and exchange ideas both internally and within the broader community.

  Additional details about the conference are available at
  <http://cfgmgmtcamp.eu/>.
