name: Config Management Camp
location: Ghent, Belgium
start: 2019-02-04
end: 2019-02-06
tags:
description: |
  We’re pleased to announce CfgMgmtCamp 2019, the sixth year and 8th edition. CfgMgmtCamp has evolved beyond pure configuration management, so we are evolving the topics and content of the conference. CfgMgmtCamp wants to bring all infrastructure management tools and principles together to share and learn.

  Additional details about the conference are available at
  <https://cfgmgmtcamp.eu/>
